function [fieldnotes]=importFieldNoteMissPACE(Workbook)
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook='C:\Users\w10139248\Documents\Oceanography\NRL_USM_PACE_2022\IOP_data\NRL_USM_PACE_IOP-CastLog.xlsx'
%    Worksheet: PACE_IOP_Log
%
% Auto-generated by MATLAB on 20-Jul-2022 15:12:58

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 17);

% Specify sheet and range
opts.Sheet = "PACE_IOP_Log";
opts.DataRange = "A2:Q59";

% Specify column names and types
opts.VariableNames = ["ObsStartTime", "StnCode", "StationName", "Lat", "Lon", "solartime", "TWD_ft", "Secchi_vis_ft", "ObsZ_ft", "T_C", "Cond", "Salinity", "ObsStopTime", "Comments", "VSF_file", "archive_file", "WAP_extracted"];
opts.VariableTypes = ["datetime", "categorical", "categorical", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "datetime", "categorical", "string", "categorical", "categorical"];

% Specify variable properties
opts = setvaropts(opts, "VSF_file", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["StnCode", "StationName", "solartime", "Comments", "VSF_file", "archive_file", "WAP_extracted"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "ObsStartTime", "InputFormat", "");
opts = setvaropts(opts, "ObsStopTime", "InputFormat", "");

% Import the data
fieldnotes = readtable(Workbook, opts, "UseExcel", false);


%% Clear temporary variables
clear opts
end